server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: api-gateway
  webflux:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER # WebFlux 专用策略
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  cloud:
    gateway:

#      httpclient:        
#         encode-url: ALWAYS # 强制启用URL编码
      routes:
        - id: gateway-swagger
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/gateway,/v3/api-docs/gateway/**
          filters:
            - RewritePath=/v3/api-docs/gateway/?(?<query>.*), /v3/api-docs?group=gateway&$\{query}
            - AddResponseHeader=Cache-Control, no-store, no-cache, must-revalidate # 添加响应头禁用缓存
                           
#        - id: provider-service # 路由ID，唯一标识
#          uri: lb://service-provider # 路由目标服务，lb表示负载均衡
#          predicates: # 路由断言，用于匹配请求
#            - Path=/ui-provider/** # 匹配路径以/products/开头的请求
#          filters: # 路由过滤器
#            - AddRequestHeader=X-Request-Id, 123456 # 添加请求头
#            - RewritePath=/ui-(?<service>[^/]+)/(?<segment>.*), /service-$\{service}/$\{segment}
#        - id: consumer-service # 新增Consumer服务的路由
#          uri: lb://service-consumer
#          predicates:
#            - Path=/ui-consumer/** # 匹配路径以/consumer/开头的请求
#          filters:
#            - AddRequestHeader=X-Consumer-Request-Id, 789012
#            - RewritePath=/ui-(?<service>[^/]+)/(?<segment>.*), /service-$\{service}/$\{segment}
#
#        - id: default-service-mapping # 默认路由
#          uri: lb://HB-QMS-Provider # 默认服务
#          predicates: # 路由断言，用于匹配请求
#            - Path=/** # 匹配所有其他路径                   

            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator  #配置端点访问前缀
      exposure:
        include: health,info,env,metrics
  info: # 显示任意的应用信息，默认关闭  springBoot版本：2.7.5 CURRENT  GA如果是更低一些的版本默认是开启的
    env:
      enabled: true
  
springdoc:
  packages-to-scan: charles.zhou.gateway.controller
  swagger-ui:
    path: /
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs/gateway
        name: Gateway
    cache:
      validator: false
    operationsSorter: method
    tagsSorter: alpha
    persistAuthorization: true
    layout: StandaloneLayout
    defaultModelExpandDepth: 3
    enabled: true
    tryItOutEnabled: true
#  api-docs:
#    path: /v3/api-docs    

info:
  app:
    name: "@project.name@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springdoc: INFO