server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: api-gateway
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    gateway:
      routes:            
        - id: product-service # 路由ID，唯一标识
          uri: lb://service-provider # 路由目标服务，lb表示负载均衡
          predicates: # 路由断言，用于匹配请求
            - Path=/ui-provider/** # 匹配路径以/products/开头的请求
          filters: # 路由过滤器
            - AddRequestHeader=X-Request-Id, 123456 # 添加请求头
            - RewritePath=/ui-(?<service>[^/]+)/(?<segment>.*), /service-$\{service}/$\{segment}
        - id: consumer-service # 新增Consumer服务的路由
          uri: lb://service-consumer
          predicates:
            - Path=/ui-consumer/** # 匹配路径以/consumer/开头的请求
          filters:
            - AddRequestHeader=X-Consumer-Request-Id, 789012
            - RewritePath=/ui-(?<service>[^/]+)/(?<segment>.*), /service-$\{service}/$\{segment}

        - id: default-service-mapping
          uri: lb://HB-QMS-Provider
          predicates:
            - Path=/** # 匹配所有其他路径
          filters:
            - RewritePath=/.*, /$\{path}
      discovery:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/ # Eureka服务注册中心地址

management:
  info: # 显示任意的应用信息，默认关闭  springBoot版本：2.7.5 CURRENT  GA如果是更低一些的版本默认是开启的
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator  #配置端点访问前缀
      exposure:
        include: info,health  #只暴露info,health两个端点; “*” 表示暴露所有端点
        exclude: health  #可以将以暴露的端点排除（不暴露）
info:
  app:
    name: "@project.name@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
#logging:
#  level:
#    org.springframework.boot.actuate.info: DEBUG