server:
  port: ${APP_PORT:8080}

spring:
  profiles:
    active: default
  application:
    name: api-gateway
  webflux:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER # WebFlux 专用策略
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  cloud:
    gateway:
      routes:
        # OpenAPI文档路由（重点修正！）
        - id: provider-swagger
          uri: lb://service-provider  # 强制指定地址避免负载均衡干扰
          predicates:
            - Path=/v3/api-docs/service-provider
          filters:
            # 精确路径重写（使用完整正则）
            - RewritePath=/v3/api-docs/service-provider/?.*, /v3/api-docs
        - id: consumer-swagger
          uri: lb://service-consumer  # 强制指定地址避免负载均衡干扰
          predicates:
            - Path=/v3/api-docs/service-consumer
          filters:  
            - RewritePath=/v3/api-docs/service-consumer/?.*, /v3/api-docs
        - id: hb-qms-swagger
          uri: lb://hb-qms-provider  
          predicates:
            - Path=/v2/api-docs/hb-qms-provider
          filters:
            - RewritePath=/v2/api-docs/hb-qms-provider/?.*, /v2/api-docs
        - id: gateway-swagger
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/gateway,/v3/api-docs/gateway/**
          filters:
            - RewritePath=/v3/api-docs/gateway/?(?<query>.*), /v3/api-docs?group=gateway&$\{query}
            - AddResponseHeader=Cache-Control, no-store, no-cache, must-revalidate # 添加响应头禁用缓存
            
            
                                       
        - id: provider-service # 路由ID，唯一标识
          uri: lb://service-provider # 路由目标服务，lb表示负载均衡
          predicates: # 路由断言，用于匹配请求
            - Path=/api/service-provider/** #, /service-provider/v3/api-docs/** 
          filters: # 路由过滤器
            - StripPrefix=1                  
        - id: consumer-service # 新增Consumer服务的路由
          uri: lb://service-consumer
          predicates:
            - Path=/api/service-consumer/**, /service-consumer/v3/api-docs/** 
          filters:
            - StripPrefix=1
        - id: hb-qms-service # 新增Consumer服务的路由
          uri: lb://hb-qms-provider
          predicates:
            - Path=/api/hb-qms-provider/**, /hb-qms-provider/v3/api-docs/** 
          filters:
            - StripPrefix=1                                    
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator  #配置端点访问前缀
      exposure:
        include: health,info,env,metrics
  info:
    env:
      enabled: true
  
springdoc:
  packages-to-scan: charles.zhou.gateway.controller
  cache:
    disabled: true  # 生产环境启用缓存
    validator: false
  swagger-ui:
    cache-control: no-store, no-cache, must-revalidate # 控制UI缓存
    path: / # 显式声明访问路径 /swagger-ui.html
    config-url: /v3/api-docs/swagger-config?nocache
    urls:
      - url: /v3/api-docs/service-consumer  # 对应网关路由路径
        name: 服务消费者
      - url: /v3/api-docs/service-provider  # 对应网关路由路径
        name: 服务提供者
      - url: /v3/api-docs/gateway
        name: 网关服务商
      - url: /v2/api-docs/hb-qms-provider
        name: 博恩QMS
    operationsSorter: method
    tagsSorter: alpha
    persistAuthorization: true
    layout: StandaloneLayout
    defaultModelExpandDepth: 3
    enabled: true
    tryItOutEnabled: true
  api-docs:
    path: /v3/api-docs # 显式指定网关自身文档路径（已禁用）
    enabled: true
    groups:
        enabled: true
info:
  app:
    name: "@project.name@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

logging:
  level:
    '[org.springframework.cloud.gateway]': INFO
    '[org.springdoc]': INFO